
spring.application.name=Mascotas

# --- CONFIGURACIÓN DE BASE DE DATOS (DATOS REALES DE RENDER) ---
# Usamos la URL externa para asegurar conexión y el prefijo jdbc: obligatorio
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d6t1mclm5p6s73b44od0-a.oregon-postgres.render.com/mascotas_db_7x6h?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mascotas_db_7x6h_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:I4d2sA3O70mgLsvt7et2UFxbHAdbVNGk}

spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- PUERTO PARA RENDER ---
server.port=${PORT:8080}