# Tu configuración actual
spring.application.name=Mascotas
spring.datasource.url=jdbc:postgresql://localhost:5432/mascotas-data-base
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresPlusDialect

#PARA VER LAS RUTAS
# Ver todos los endpoints mapeados
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG

# Opcional: Ver más detalles de Spring Web
logging.level.org.springframework.web=DEBUG

